name: "Greet someone"
description: "Greet someone"

inputs:
  greeting:
    description: "Greeting"
    required: true
    default: "Hello"
  name: 
    description: "Who to greet"
    required: true
    default: "Bo"
  outputs:
    greeting-text:
      description: "Greeting Text"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.greeting }}
    - ${{ inputs.name }}
    
